
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity xadc_controller is
  Port (
    clk_i            : in  std_logic;                      -- 100 MHz system clock
    rstn_i           : in  std_logic;                      -- active low reset

    -- Analog inputs (connect to FPGA pins via XDC)
    vp_in            : in  std_logic;                      -- VP dedicated input
    vn_in            : in  std_logic;                      -- VN dedicated input
--    vauxp0           : in  std_logic;                      -- VAUX0 positive
--    vauxn0           : in  std_logic;                      -- VAUX0 negative
--    vauxp1           : in  std_logic;                      -- VAUX1 positive
--    vauxn1           : in  std_logic;                      -- VAUX1 negative

    -- ADC results (16-bit, 12 MSBs are the ADC value)
    xadc_data_vp_vn  : out std_logic_vector(15 downto 0);  -- VP/VN result
    xadc_data_vaux0  : out std_logic_vector(15 downto 0);  -- VAUX0 result
    xadc_data_vaux1  : out std_logic_vector(15 downto 0);  -- VAUX1 result

    -- Status signals
    xadc_eoc         : out std_logic;                      -- End of conversion
    xadc_eos         : out std_logic;                      -- End of sequence
    xadc_busy        : out std_logic;                      -- XADC busy
    xadc_channel     : out std_logic_vector(4 downto 0);   -- Current channel
    xadc_alarm       : out std_logic    -- Alarm flags
  );
end xadc_controller;

architecture Behavioral of xadc_controller is

  -- XADC Wizard IP component declaration
  -- (generated by Vivado when you add the IP)
  component xadc_wiz_0
   port
   (
    daddr_in        : in  STD_LOGIC_VECTOR (6 downto 0);     -- Address bus for the dynamic reconfiguration port
    den_in          : in  STD_LOGIC;                         -- Enable Signal for the dynamic reconfiguration port
    di_in           : in  STD_LOGIC_VECTOR (15 downto 0);    -- Input data bus for the dynamic reconfiguration port
    dwe_in          : in  STD_LOGIC;                         -- Write Enable for the dynamic reconfiguration port
    do_out          : out  STD_LOGIC_VECTOR (15 downto 0);   -- Output data bus for dynamic reconfiguration port
    drdy_out        : out  STD_LOGIC;                        -- Data ready signal for the dynamic reconfiguration port
    dclk_in         : in  STD_LOGIC;                         -- Clock input for the dynamic reconfiguration port
    reset_in        : in  STD_LOGIC;                         -- Reset signal for the System Monitor control logic
    busy_out        : out  STD_LOGIC;                        -- ADC Busy signal
    channel_out     : out  STD_LOGIC_VECTOR (4 downto 0);    -- Channel Selection Outputs
    eoc_out         : out  STD_LOGIC;                        -- End of Conversion Signal
    eos_out         : out  STD_LOGIC;                        -- End of Sequence Signal
    ot_out          : out  STD_LOGIC;                        -- Over-Temperature alarm output
    vccaux_alarm_out : out  STD_LOGIC;                        -- VCCAUX-sensor alarm output
    vccint_alarm_out : out  STD_LOGIC;                        -- VCCINT-sensor alarm output
    user_temp_alarm_out : out  STD_LOGIC;                        -- Temperature-sensor alarm output
    alarm_out       : out STD_LOGIC;                         -- OR'ed output of all the Alarms
    muxaddr_out     : out STD_LOGIC_VECTOR(4 downto 0); 
    vp_in           : in  STD_LOGIC;                         -- Dedicated Analog Input Pair
    vn_in           : in  STD_LOGIC
);
  end component;

  -- Internal signals
  signal xadc_rst       : std_logic;
  signal xadc_do        : std_logic_vector(15 downto 0);
  signal xadc_drdy      : std_logic;
  signal xadc_eoc_int   : std_logic;
  signal xadc_eos_int   : std_logic;
  signal xadc_busy_int  : std_logic;
  signal xadc_chan      : std_logic_vector(4 downto 0);
  signal xadc_alarm_int : std_logic;
  signal xadc_muxaddr   : std_logic_vector(4 downto 0);
  signal xadc_ot        : std_logic;
  signal xadc_vccaux_alarm : std_logic;
  signal xadc_vccint_alarm : std_logic;
  signal xadc_user_temp_alarm : std_logic;

  -- DRP interface (read-only mode, write disabled)
  signal daddr          : std_logic_vector(6 downto 0);
  signal den            : std_logic;

  -- Stored ADC results
  signal reg_vp_vn      : std_logic_vector(15 downto 0) := (others => '0');
--  signal reg_vaux0      : std_logic_vector(15 downto 0) := (others => '0');
--  signal reg_vaux1      : std_logic_vector(15 downto 0) := (others => '0');

  -- Channel address constants for DRP readout
  -- VP/VN = channel 3  -> DRP address 0x03
  -- VAUX0 = channel 16 -> DRP address 0x10
  -- VAUX1 = channel 17 -> DRP address 0x11
  constant CHAN_VPVN  : std_logic_vector(4 downto 0) := "00011"; -- ch3
--  constant CHAN_VAUX0 : std_logic_vector(4 downto 0) := "10000"; -- ch16
--  constant CHAN_VAUX1 : std_logic_vector(4 downto 0) := "10001"; -- ch17

  -- State machine for DRP readout after EOC
  type drp_state_t is (IDLE, WAIT_EOC, READ_RESULT, WAIT_DRDY);
  signal drp_state : drp_state_t := IDLE;

begin

  xadc_rst <= not rstn_i;

  -- XADC Wizard instantiation
  xadc_wiz_inst : xadc_wiz_0
    port map (
      dclk_in             => clk_i,
      reset_in            => xadc_rst,
      vp_in               => vp_in,
      vn_in               => vn_in,
      daddr_in            => daddr,
      den_in              => den,
      dwe_in              => '0',
      di_in               => (others => '0'),
      do_out              => xadc_do,
      drdy_out            => xadc_drdy,
      eoc_out             => xadc_eoc_int,
      eos_out             => xadc_eos_int,
      busy_out            => xadc_busy_int,
      channel_out         => xadc_chan,
      ot_out              => xadc_ot,
      vccaux_alarm_out    => xadc_vccaux_alarm,
      vccint_alarm_out    => xadc_vccint_alarm,
      user_temp_alarm_out => xadc_user_temp_alarm,
      alarm_out           => xadc_alarm_int,
      muxaddr_out         => xadc_muxaddr
    );

  -- Connect status outputs
  xadc_eoc     <= xadc_eoc_int;
  xadc_eos     <= xadc_eos_int;
  xadc_busy    <= xadc_busy_int;
  xadc_channel <= xadc_chan;
  xadc_alarm   <= xadc_alarm_int;

  -- DRP read state machine: captures result after each EOC
  drp_read_proc : process(clk_i, rstn_i)
  begin
    if rstn_i = '0' then
      drp_state  <= IDLE;
      den        <= '0';
      daddr      <= (others => '0');
      reg_vp_vn  <= (others => '0');

    elsif rising_edge(clk_i) then
      den <= '0'; -- default: no DRP read

      case drp_state is

        when IDLE =>
          drp_state <= WAIT_EOC;

        when WAIT_EOC =>
          -- Wait for end of conversion, then read VP/VN channel
          if xadc_eoc_int = '1' then
            daddr     <= "0000011";  -- DRP address 0x03 = VP/VN
            den       <= '1';
            drp_state <= WAIT_DRDY;
          end if;

        when WAIT_DRDY =>
          if xadc_drdy = '1' then
            reg_vp_vn <= xadc_do;
            drp_state <= WAIT_EOC;
          end if;

        when others =>
          drp_state <= IDLE;

      end case;
    end if;
  end process;

  -- Output registered value
  xadc_data_vp_vn <= reg_vp_vn;

end Behavioral;