--==========================================================================--
-- Network Name: f_Loc_1_Sync_SA_Diff_top                                   --
-- Generated For: The University Of York                                    --
-- Generated On: Nov-27-2023                                                --
--==========================================================================--
--     Network generated by Daniel Thompson's microcircuit to VHDL tool     --
--==========================================================================--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use IEEE.fixed_pkg.all;
use work.DigEng.all;
use work.array_type.ALL;

entity f_Loc_1_Sync_SA_Diff_top is
    generic(dendrite_NO : integer := 11;
            neuron_NO : integer := 20;
            weights_array : array_3d_SFIXED(0 to neuron_NO-1)(0 to dendrite_NO-1)(1 downto -6) :=
            (
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(-2.16119748, 1, -6), to_SFIXED(-5.63897155, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(0.01505309, 1, -6), to_SFIXED(0.36151544, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(-2.23786074, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(-1.25651735, 1, -6), to_SFIXED(-6.25626291, 1, -6), to_SFIXED(0.39472189, 1, -6), to_SFIXED(-1.06822882, 1, -6), to_SFIXED(-4.00542076, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.06810841, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(0.34306959, 1, -6), to_SFIXED(1.08057893, 1, -6), to_SFIXED(1.00508014, 1, -6), to_SFIXED(-2.30140000, 1, -6), to_SFIXED(0.52942359, 1, -6), to_SFIXED(0.08680776, 1, -6), to_SFIXED(-2.06036421, 1, -6), to_SFIXED(0.43404360, 1, -6)),
            (to_SFIXED(0.99264855, 1, -6), to_SFIXED(-2.48403934, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(0.78190567, 1, -6), to_SFIXED(0.91291837, 1, -6), to_SFIXED(-1.04158563, 1, -6), to_SFIXED(-0.15226972, 1, -6), to_SFIXED(-0.11788958, 1, -6), to_SFIXED(0.04648864, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(0.91254481, 1, -6), to_SFIXED(-1.10478487, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(0.05985730, 1, -6), to_SFIXED(-1.83602198, 1, -6), to_SFIXED(-5.64798116, 1, -6), to_SFIXED(0.98555175, 1, -6), to_SFIXED(-6.49490909, 1, -6), to_SFIXED(0.93588218, 1, -6), to_SFIXED(-1.33185309, 1, -6)),
            (to_SFIXED(-5.27360071, 1, -6), to_SFIXED(-4.25872523, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(-5.64279200, 1, -6), to_SFIXED(-2.89304839, 1, -6), to_SFIXED(-0.45248573, 1, -6), to_SFIXED(-1.38599127, 1, -6), to_SFIXED(-0.52492929, 1, -6), to_SFIXED(-5.06535818, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(-1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(-1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(-4.67570468, 1, -6), to_SFIXED(0.49674692, 1, -6), to_SFIXED(-0.82386342, 1, -6), to_SFIXED(0.40159310, 1, -6), to_SFIXED(0.73354671, 1, -6), to_SFIXED(1.02235338, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.08921358, 1, -6), to_SFIXED(-6.45035823, 1, -6), to_SFIXED(0.97138364, 1, -6), to_SFIXED(0.56049026, 1, -6), to_SFIXED(0.61789150, 1, -6), to_SFIXED(0.20150560, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.10000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(-1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)),
            (to_SFIXED(1.10000000, 1, -6), to_SFIXED(-1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6), to_SFIXED(1.00000000, 1, -6)))
            );

            -- weight connections 
            -- N:X is signal from neuron X
            -- I:X is signal from input X
            -- n/c is no connection
            --
            -- 		 neuron 0 | N:3 | N:6 | N:7 | n/c | n/c | n/c | n/c | n/c | n/c | I:4 | I:0 | 		 --
            -- 		 neuron 1 | N:2 | N:7 | n/c | n/c | n/c | n/c | I:6 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 2 | N:0 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 3 | N:1 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 4 | N:3 | n/c | n/c | I:7 | I:6 | I:5 | I:4 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 5 | N:2 | N:3 | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:4 | I:3 | I:0 | 		 --
            -- 		 neuron 6 | N:4 | N:5 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 7 | N:4 | N:5 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 8 | N:16 | N:17 | n/c | n/c | I:7 | I:6 | I:4 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 9 | N:16 | N:17 | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:3 | I:1 | I:0 | 		 --
            -- 		 neuron 10 | N:8 | N:13 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 11 | N:9 | N:12 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 12 | N:10 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 13 | N:11 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 14 | n/c | n/c | n/c | n/c | n/c | I:6 | I:4 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 15 | n/c | n/c | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:4 | I:3 | I:1 | 		 --
            -- 		 neuron 16 | N:14 | N:15 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 17 | N:14 | N:15 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 18 | N:7 | N:18 | N:19 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 19 | N:17 | N:18 | N:19 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --

    port (clk, rst, en : in std_logic;
          Spike_in : in std_logic_vector(0 to 7);
          Spikes_out : out std_logic_vector(0 to 1);
          STDP_en : in std_logic;
          weight_rst : in std_logic);

end f_Loc_1_Sync_SA_Diff_top;

architecture Behavioral of f_Loc_1_Sync_SA_Diff_top is 

signal neuron_ins : array_2d_std(0 to neuron_NO-1)(0 to dendrite_NO-1);
signal spike_out_int : STD_LOGIC_VECTOR (0 to neuron_NO-1);

begin
neurons: for i in 0 to (neuron_NO-1) generate	-- generates neuron_NO number of neurons
    neuron: entity work.neuron_top_level
        generic map(dendrite_NO => dendrite_NO,
        weights_generic => weights_array(i)(0 to dendrite_NO-1))
        port map(clk=> clk, rst => rst, en => en,
                 Spike_in => neuron_ins(i),
                 Spike_out => spike_out_int(i),
                 STDP_en => STDP_en,
                 weight_rst => weight_rst);
end generate;

--internal signal allocations
neuron_ins(2)(0) <= spike_out_int(0); 	-- Neuron:0 -> neuron:2, dendrite:0
neuron_ins(3)(0) <= spike_out_int(1); 	-- Neuron:1 -> neuron:3, dendrite:0
neuron_ins(1)(0) <= spike_out_int(2); 	-- Neuron:2 -> neuron:1, dendrite:0
neuron_ins(5)(0) <= spike_out_int(2); 	-- Neuron:2 -> neuron:5, dendrite:0
neuron_ins(0)(0) <= spike_out_int(3); 	-- Neuron:3 -> neuron:0, dendrite:0
neuron_ins(4)(0) <= spike_out_int(3); 	-- Neuron:3 -> neuron:4, dendrite:0
neuron_ins(5)(1) <= spike_out_int(3); 	-- Neuron:3 -> neuron:5, dendrite:1
neuron_ins(6)(0) <= spike_out_int(4); 	-- Neuron:4 -> neuron:6, dendrite:0
neuron_ins(7)(0) <= spike_out_int(4); 	-- Neuron:4 -> neuron:7, dendrite:0
neuron_ins(6)(1) <= spike_out_int(5); 	-- Neuron:5 -> neuron:6, dendrite:1
neuron_ins(7)(1) <= spike_out_int(5); 	-- Neuron:5 -> neuron:7, dendrite:1
neuron_ins(0)(1) <= spike_out_int(6); 	-- Neuron:6 -> neuron:0, dendrite:1
neuron_ins(0)(2) <= spike_out_int(7); 	-- Neuron:7 -> neuron:0, dendrite:2
neuron_ins(1)(1) <= spike_out_int(7); 	-- Neuron:7 -> neuron:1, dendrite:1
neuron_ins(18)(0) <= spike_out_int(7); 	-- Neuron:7 -> neuron:18, dendrite:0
neuron_ins(10)(0) <= spike_out_int(8); 	-- Neuron:8 -> neuron:10, dendrite:0
neuron_ins(11)(0) <= spike_out_int(9); 	-- Neuron:9 -> neuron:11, dendrite:0
neuron_ins(12)(0) <= spike_out_int(10); 	-- Neuron:10 -> neuron:12, dendrite:0
neuron_ins(13)(0) <= spike_out_int(11); 	-- Neuron:11 -> neuron:13, dendrite:0
neuron_ins(11)(1) <= spike_out_int(12); 	-- Neuron:12 -> neuron:11, dendrite:1
neuron_ins(10)(1) <= spike_out_int(13); 	-- Neuron:13 -> neuron:10, dendrite:1
neuron_ins(16)(0) <= spike_out_int(14); 	-- Neuron:14 -> neuron:16, dendrite:0
neuron_ins(17)(0) <= spike_out_int(14); 	-- Neuron:14 -> neuron:17, dendrite:0
neuron_ins(16)(1) <= spike_out_int(15); 	-- Neuron:15 -> neuron:16, dendrite:1
neuron_ins(17)(1) <= spike_out_int(15); 	-- Neuron:15 -> neuron:17, dendrite:1
neuron_ins(8)(0) <= spike_out_int(16); 	-- Neuron:16 -> neuron:8, dendrite:0
neuron_ins(9)(0) <= spike_out_int(16); 	-- Neuron:16 -> neuron:9, dendrite:0
neuron_ins(8)(1) <= spike_out_int(17); 	-- Neuron:17 -> neuron:8, dendrite:1
neuron_ins(9)(1) <= spike_out_int(17); 	-- Neuron:17 -> neuron:9, dendrite:1
neuron_ins(19)(0) <= spike_out_int(17); 	-- Neuron:17 -> neuron:19, dendrite:0
neuron_ins(18)(1) <= spike_out_int(18); 	-- Neuron:18 -> neuron:18, dendrite:1
neuron_ins(19)(1) <= spike_out_int(18); 	-- Neuron:18 -> neuron:19, dendrite:1
neuron_ins(18)(2) <= spike_out_int(19); 	-- Neuron:19 -> neuron:18, dendrite:2
neuron_ins(19)(2) <= spike_out_int(19); 	-- Neuron:19 -> neuron:19, dendrite:2

--Input signal allocations
neuron_ins(0)(10) <= Spike_in(7); 	-- Input:0 -> neuron:0, dendrite:10
neuron_ins(1)(10) <= Spike_in(7); 	-- Input:0 -> neuron:1, dendrite:10
neuron_ins(4)(10) <= Spike_in(7); 	-- Input:0 -> neuron:4, dendrite:10
neuron_ins(5)(10) <= Spike_in(7); 	-- Input:0 -> neuron:5, dendrite:10
neuron_ins(8)(10) <= Spike_in(7); 	-- Input:0 -> neuron:8, dendrite:10
neuron_ins(9)(10) <= Spike_in(7); 	-- Input:0 -> neuron:9, dendrite:10
neuron_ins(14)(10) <= Spike_in(7); 	-- Input:0 -> neuron:14, dendrite:10
neuron_ins(1)(9) <= Spike_in(6); 	-- Input:1 -> neuron:1, dendrite:9
neuron_ins(4)(9) <= Spike_in(6); 	-- Input:1 -> neuron:4, dendrite:9
neuron_ins(8)(9) <= Spike_in(6); 	-- Input:1 -> neuron:8, dendrite:9
neuron_ins(9)(9) <= Spike_in(6); 	-- Input:1 -> neuron:9, dendrite:9
neuron_ins(14)(9) <= Spike_in(6); 	-- Input:1 -> neuron:14, dendrite:9
neuron_ins(15)(10) <= Spike_in(6); 	-- Input:1 -> neuron:15, dendrite:10
neuron_ins(1)(8) <= Spike_in(5); 	-- Input:2 -> neuron:1, dendrite:8
neuron_ins(4)(8) <= Spike_in(5); 	-- Input:2 -> neuron:4, dendrite:8
neuron_ins(8)(8) <= Spike_in(5); 	-- Input:2 -> neuron:8, dendrite:8
neuron_ins(14)(8) <= Spike_in(5); 	-- Input:2 -> neuron:14, dendrite:8
neuron_ins(1)(7) <= Spike_in(4); 	-- Input:3 -> neuron:1, dendrite:7
neuron_ins(4)(7) <= Spike_in(4); 	-- Input:3 -> neuron:4, dendrite:7
neuron_ins(5)(9) <= Spike_in(4); 	-- Input:3 -> neuron:5, dendrite:9
neuron_ins(8)(7) <= Spike_in(4); 	-- Input:3 -> neuron:8, dendrite:7
neuron_ins(9)(8) <= Spike_in(4); 	-- Input:3 -> neuron:9, dendrite:8
neuron_ins(14)(7) <= Spike_in(4); 	-- Input:3 -> neuron:14, dendrite:7
neuron_ins(15)(9) <= Spike_in(4); 	-- Input:3 -> neuron:15, dendrite:9
neuron_ins(0)(9) <= Spike_in(3); 	-- Input:4 -> neuron:0, dendrite:9
neuron_ins(4)(6) <= Spike_in(3); 	-- Input:4 -> neuron:4, dendrite:6
neuron_ins(5)(8) <= Spike_in(3); 	-- Input:4 -> neuron:5, dendrite:8
neuron_ins(8)(6) <= Spike_in(3); 	-- Input:4 -> neuron:8, dendrite:6
neuron_ins(14)(6) <= Spike_in(3); 	-- Input:4 -> neuron:14, dendrite:6
neuron_ins(15)(8) <= Spike_in(3); 	-- Input:4 -> neuron:15, dendrite:8
neuron_ins(4)(5) <= Spike_in(2); 	-- Input:5 -> neuron:4, dendrite:5
neuron_ins(5)(7) <= Spike_in(2); 	-- Input:5 -> neuron:5, dendrite:7
neuron_ins(9)(7) <= Spike_in(2); 	-- Input:5 -> neuron:9, dendrite:7
neuron_ins(15)(7) <= Spike_in(2); 	-- Input:5 -> neuron:15, dendrite:7
neuron_ins(1)(6) <= Spike_in(1); 	-- Input:6 -> neuron:1, dendrite:6
neuron_ins(4)(4) <= Spike_in(1); 	-- Input:6 -> neuron:4, dendrite:4
neuron_ins(5)(6) <= Spike_in(1); 	-- Input:6 -> neuron:5, dendrite:6
neuron_ins(8)(5) <= Spike_in(1); 	-- Input:6 -> neuron:8, dendrite:5
neuron_ins(9)(6) <= Spike_in(1); 	-- Input:6 -> neuron:9, dendrite:6
neuron_ins(14)(5) <= Spike_in(1); 	-- Input:6 -> neuron:14, dendrite:5
neuron_ins(15)(6) <= Spike_in(1); 	-- Input:6 -> neuron:15, dendrite:6
neuron_ins(4)(3) <= Spike_in(0); 	-- Input:7 -> neuron:4, dendrite:3
neuron_ins(5)(5) <= Spike_in(0); 	-- Input:7 -> neuron:5, dendrite:5
neuron_ins(8)(4) <= Spike_in(0); 	-- Input:7 -> neuron:8, dendrite:4
neuron_ins(9)(5) <= Spike_in(0); 	-- Input:7 -> neuron:9, dendrite:5
neuron_ins(15)(5) <= Spike_in(0); 	-- Input:7 -> neuron:15, dendrite:5

--Output signal allocations
Spikes_out(0) <= spike_out_int(18);	-- Neuron 18 -> output 0
Spikes_out(1) <= spike_out_int(19);  	-- Neuron 19 -> output 1
