--==========================================================================--
-- Network Name: f_Loc_1_Comb_SA_Diff_top                                   --
-- Generated For: The University Of York                                    --
-- Generated On: Nov-27-2023                                                --
--==========================================================================--
--     Network generated by Daniel Thompson's microcircuit to VHDL tool     --
--==========================================================================--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use IEEE.fixed_pkg.all;
library micro_ckt_pkg_lib;
use micro_ckt_pkg_lib.array_type.all;
use micro_ckt_pkg_lib.DigEng.all;
library micro_ckt_lib;
use micro_ckt_lib. micro_circuit_pkg.all;

entity f_Loc_1_Comb_SA_Diff_top is
    generic(dendrite_NO : integer := 11;
            neuron_NO : integer := 14;
            weights_array : array_3d_SFIXED(0 to neuron_NO-1)(0 to dendrite_NO-1)(4 downto -6) :=
            (
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(0.43528983, 4, -6), to_SFIXED(-4.72688100, 4, -6), to_SFIXED(-0.43408621, 4, -6), to_SFIXED(0.58161537, 4, -6), to_SFIXED(0.11846055, 4, -6), to_SFIXED(-5.85423208, 4, -6), to_SFIXED(0.99634725, 4, -6)),
            (to_SFIXED(-5.41759901, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(-3.91156189, 4, -6), to_SFIXED(0.81870513, 4, -6), to_SFIXED(-3.38965642, 4, -6), to_SFIXED(-4.64689989, 4, -6), to_SFIXED(-4.01846715, 4, -6), to_SFIXED(-6.72101514, 4, -6), to_SFIXED(-1.41464199, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.09502853, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(-0.89067404, 4, -6), to_SFIXED(-5.07399142, 4, -6), to_SFIXED(0.74035186, 4, -6), to_SFIXED(-0.33272554, 4, -6), to_SFIXED(0.39348798, 4, -6), to_SFIXED(0.46501243, 4, -6), to_SFIXED(0.52616561, 4, -6), to_SFIXED(0.90778084, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(0.69840177, 4, -6), to_SFIXED(0.78663258, 4, -6), to_SFIXED(0.72737885, 4, -6), to_SFIXED(-0.97750879, 4, -6), to_SFIXED(-0.04010293, 4, -6)),
            (to_SFIXED(0.72496092, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(0.68534698, 4, -6), to_SFIXED(0.61580474, 4, -6), to_SFIXED(-3.43988451, 4, -6), to_SFIXED(0.69813318, 4, -6), to_SFIXED(-2.54899903, 4, -6), to_SFIXED(0.81931506, 4, -6), to_SFIXED(0.29203706, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(0.64978890, 4, -6), to_SFIXED(0.39279362, 4, -6), to_SFIXED(-2.85518365, 4, -6), to_SFIXED(-6.17209136, 4, -6), to_SFIXED(1.03486590, 4, -6), to_SFIXED(-3.94897582, 4, -6)),
            (to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.10000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(-1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)),
            (to_SFIXED(1.10000000, 4, -6), to_SFIXED(-1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6), to_SFIXED(1.00000000, 4, -6)))
            );

            -- weight connections 
            -- N:X is signal from neuron X
            -- I:X is signal from input X
            -- n/c is no connection
            --
            -- 		 neuron 0 | n/c | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 1 | N:5 | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:4 | I:3 | I:1 | I:0 | 		 --
            -- 		 neuron 2 | N:0 | N:1 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 3 | N:0 | N:1 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 4 | N:3 | N:5 | n/c | I:7 | I:6 | I:5 | I:4 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 5 | N:4 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 6 | n/c | n/c | n/c | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:1 | I:0 | 		 --
            -- 		 neuron 7 | N:11 | n/c | n/c | n/c | I:7 | I:6 | I:4 | I:3 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 8 | N:6 | N:7 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 9 | N:6 | N:7 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 10 | N:11 | n/c | n/c | n/c | n/c | I:7 | I:6 | I:5 | I:2 | I:1 | I:0 | 		 --
            -- 		 neuron 11 | N:10 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 12 | N:5 | N:12 | N:13 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --
            -- 		 neuron 13 | N:9 | N:12 | N:13 | n/c | n/c | n/c | n/c | n/c | n/c | n/c | n/c | 		 --

    port (clk, rst, en : in std_logic;
          Spike_in : in std_logic_vector(0 to 7);
          Spikes_out : out std_logic_vector(0 to 1);
          STDP_en : in std_logic;
          weight_rst : in std_logic);

end f_Loc_1_Comb_SA_Diff_top;

architecture Behavioral of f_Loc_1_Comb_SA_Diff_top is 

signal neuron_ins : array_2d_std(0 to neuron_NO-1)(0 to dendrite_NO-1);
signal spike_out_int : STD_LOGIC_VECTOR (0 to neuron_NO-1);

attribute keep: boolean;              
attribute keep of neuron_ins : signal is true;
attribute keep of spike_out_int : signal is true;

attribute mark_debug : string;
attribute MARK_DEBUG of neuron_ins : signal is "TRUE";
attribute MARK_DEBUG of spike_out_int : signal is "TRUE";

begin
neurons: for i in 0 to (neuron_NO-1) generate	-- generates neuron_NO number of neurons
    neuron: neuron_top_level
        generic map(dendrite_NO => dendrite_NO,
        weights_generic => weights_array(i)(0 to dendrite_NO-1))
        port map(clk=> clk, rst => rst, en => en,
                 Spike_in => neuron_ins(i),
                 Spike_out => spike_out_int(i),
                 STDP_en => STDP_en,
         	 weight_rst => weight_rst);
end generate;

--internal signal allocations
neuron_ins(2)(0) <= spike_out_int(0); 	-- Neuron:0 -> neuron:2, dendrite:0
neuron_ins(3)(0) <= spike_out_int(0); 	-- Neuron:0 -> neuron:3, dendrite:0
neuron_ins(2)(1) <= spike_out_int(1); 	-- Neuron:1 -> neuron:2, dendrite:1
neuron_ins(3)(1) <= spike_out_int(1); 	-- Neuron:1 -> neuron:3, dendrite:1
neuron_ins(4)(0) <= spike_out_int(3); 	-- Neuron:3 -> neuron:4, dendrite:0
neuron_ins(5)(0) <= spike_out_int(4); 	-- Neuron:4 -> neuron:5, dendrite:0
neuron_ins(1)(0) <= spike_out_int(5); 	-- Neuron:5 -> neuron:1, dendrite:0
neuron_ins(4)(1) <= spike_out_int(5); 	-- Neuron:5 -> neuron:4, dendrite:1
neuron_ins(12)(0) <= spike_out_int(5); 	-- Neuron:5 -> neuron:12, dendrite:0
neuron_ins(8)(0) <= spike_out_int(6); 	-- Neuron:6 -> neuron:8, dendrite:0
neuron_ins(9)(0) <= spike_out_int(6); 	-- Neuron:6 -> neuron:9, dendrite:0
neuron_ins(8)(1) <= spike_out_int(7); 	-- Neuron:7 -> neuron:8, dendrite:1
neuron_ins(9)(1) <= spike_out_int(7); 	-- Neuron:7 -> neuron:9, dendrite:1
neuron_ins(13)(0) <= spike_out_int(9); 	-- Neuron:9 -> neuron:13, dendrite:0
neuron_ins(11)(0) <= spike_out_int(10); 	-- Neuron:10 -> neuron:11, dendrite:0
neuron_ins(7)(0) <= spike_out_int(11); 	-- Neuron:11 -> neuron:7, dendrite:0
neuron_ins(10)(0) <= spike_out_int(11); 	-- Neuron:11 -> neuron:10, dendrite:0
neuron_ins(12)(1) <= spike_out_int(12); 	-- Neuron:12 -> neuron:12, dendrite:1
neuron_ins(13)(1) <= spike_out_int(12); 	-- Neuron:12 -> neuron:13, dendrite:1
neuron_ins(12)(2) <= spike_out_int(13); 	-- Neuron:13 -> neuron:12, dendrite:2
neuron_ins(13)(2) <= spike_out_int(13); 	-- Neuron:13 -> neuron:13, dendrite:2

--Input signal allocations
neuron_ins(0)(10) <= Spike_in(0); 	-- Input:0 -> neuron:0, dendrite:10
neuron_ins(1)(10) <= Spike_in(0); 	-- Input:0 -> neuron:1, dendrite:10
neuron_ins(4)(10) <= Spike_in(0); 	-- Input:0 -> neuron:4, dendrite:10
neuron_ins(6)(10) <= Spike_in(0); 	-- Input:0 -> neuron:6, dendrite:10
neuron_ins(7)(10) <= Spike_in(0); 	-- Input:0 -> neuron:7, dendrite:10
neuron_ins(10)(10) <= Spike_in(0); 	-- Input:0 -> neuron:10, dendrite:10
neuron_ins(0)(9) <= Spike_in(1); 	-- Input:1 -> neuron:0, dendrite:9
neuron_ins(1)(9) <= Spike_in(1); 	-- Input:1 -> neuron:1, dendrite:9
neuron_ins(4)(9) <= Spike_in(1); 	-- Input:1 -> neuron:4, dendrite:9
neuron_ins(6)(9) <= Spike_in(1); 	-- Input:1 -> neuron:6, dendrite:9
neuron_ins(7)(9) <= Spike_in(1); 	-- Input:1 -> neuron:7, dendrite:9
neuron_ins(10)(9) <= Spike_in(1); 	-- Input:1 -> neuron:10, dendrite:9
neuron_ins(0)(8) <= Spike_in(2); 	-- Input:2 -> neuron:0, dendrite:8
neuron_ins(4)(8) <= Spike_in(2); 	-- Input:2 -> neuron:4, dendrite:8
neuron_ins(7)(8) <= Spike_in(2); 	-- Input:2 -> neuron:7, dendrite:8
neuron_ins(10)(8) <= Spike_in(2); 	-- Input:2 -> neuron:10, dendrite:8
neuron_ins(0)(7) <= Spike_in(3); 	-- Input:3 -> neuron:0, dendrite:7
neuron_ins(1)(8) <= Spike_in(3); 	-- Input:3 -> neuron:1, dendrite:8
neuron_ins(4)(7) <= Spike_in(3); 	-- Input:3 -> neuron:4, dendrite:7
neuron_ins(7)(7) <= Spike_in(3); 	-- Input:3 -> neuron:7, dendrite:7
neuron_ins(1)(7) <= Spike_in(4); 	-- Input:4 -> neuron:1, dendrite:7
neuron_ins(4)(6) <= Spike_in(4); 	-- Input:4 -> neuron:4, dendrite:6
neuron_ins(7)(6) <= Spike_in(4); 	-- Input:4 -> neuron:7, dendrite:6
neuron_ins(0)(6) <= Spike_in(5); 	-- Input:5 -> neuron:0, dendrite:6
neuron_ins(1)(6) <= Spike_in(5); 	-- Input:5 -> neuron:1, dendrite:6
neuron_ins(4)(5) <= Spike_in(5); 	-- Input:5 -> neuron:4, dendrite:5
neuron_ins(6)(8) <= Spike_in(5); 	-- Input:5 -> neuron:6, dendrite:8
neuron_ins(10)(7) <= Spike_in(5); 	-- Input:5 -> neuron:10, dendrite:7
neuron_ins(0)(5) <= Spike_in(6); 	-- Input:6 -> neuron:0, dendrite:5
neuron_ins(1)(5) <= Spike_in(6); 	-- Input:6 -> neuron:1, dendrite:5
neuron_ins(4)(4) <= Spike_in(6); 	-- Input:6 -> neuron:4, dendrite:4
neuron_ins(6)(7) <= Spike_in(6); 	-- Input:6 -> neuron:6, dendrite:7
neuron_ins(7)(5) <= Spike_in(6); 	-- Input:6 -> neuron:7, dendrite:5
neuron_ins(10)(6) <= Spike_in(6); 	-- Input:6 -> neuron:10, dendrite:6
neuron_ins(0)(4) <= Spike_in(7); 	-- Input:7 -> neuron:0, dendrite:4
neuron_ins(1)(4) <= Spike_in(7); 	-- Input:7 -> neuron:1, dendrite:4
neuron_ins(4)(3) <= Spike_in(7); 	-- Input:7 -> neuron:4, dendrite:3
neuron_ins(6)(6) <= Spike_in(7); 	-- Input:7 -> neuron:6, dendrite:6
neuron_ins(7)(4) <= Spike_in(7); 	-- Input:7 -> neuron:7, dendrite:4
neuron_ins(10)(5) <= Spike_in(7); 	-- Input:7 -> neuron:10, dendrite:5

--Output signal allocations
Spikes_out(0) <= spike_out_int(12);	-- Neuron 12 -> output 0
Spikes_out(1) <= spike_out_int(13);  	-- Neuron 13 -> output 1	

end Behavioral;